# Generated by Django 4.2.5 on 2024-08-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dbu8nqoae/image/upload/v1/media/default_post_htbmpw', upload_to='images/'),
        ),
    ]
