# Generated by Django 4.2.5 on 2024-08-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dbu8nqoae/image/upload/v1/media/default_profile_bmg6u5', upload_to='images/'),
        ),
    ]
